# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v1 import policy_pb2 as v1_dot_policy__pb2


class PolicyDecisionPointStub(object):
    """Dịch vụ PDP (Policy Decision Point)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAccess = channel.unary_unary(
                '/policy.v1.PolicyDecisionPoint/CheckAccess',
                request_serializer=v1_dot_policy__pb2.CheckAccessRequest.SerializeToString,
                response_deserializer=v1_dot_policy__pb2.CheckAccessResponse.FromString,
                _registered_method=True)
        self.ExplainDecision = channel.unary_unary(
                '/policy.v1.PolicyDecisionPoint/ExplainDecision',
                request_serializer=v1_dot_policy__pb2.ExplainRequest.SerializeToString,
                response_deserializer=v1_dot_policy__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.RevokeDelegation = channel.unary_unary(
                '/policy.v1.PolicyDecisionPoint/RevokeDelegation',
                request_serializer=v1_dot_policy__pb2.RevokeRequest.SerializeToString,
                response_deserializer=v1_dot_policy__pb2.RevokeResponse.FromString,
                _registered_method=True)


class PolicyDecisionPointServicer(object):
    """Dịch vụ PDP (Policy Decision Point)
    """

    def CheckAccess(self, request, context):
        """Đánh giá quyền truy cập dựa trên ngữ cảnh động
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainDecision(self, request, context):
        """Đánh giá quyền kèm giải thích chi tiết các luật áp dụng
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeDelegation(self, request, context):
        """Thu hồi phiên ủy quyền của Tác tử AI tức thời (In-Memory Revocation < 1 µs)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyDecisionPointServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAccess,
                    request_deserializer=v1_dot_policy__pb2.CheckAccessRequest.FromString,
                    response_serializer=v1_dot_policy__pb2.CheckAccessResponse.SerializeToString,
            ),
            'ExplainDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainDecision,
                    request_deserializer=v1_dot_policy__pb2.ExplainRequest.FromString,
                    response_serializer=v1_dot_policy__pb2.ExplainResponse.SerializeToString,
            ),
            'RevokeDelegation': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeDelegation,
                    request_deserializer=v1_dot_policy__pb2.RevokeRequest.FromString,
                    response_serializer=v1_dot_policy__pb2.RevokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy.v1.PolicyDecisionPoint', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy.v1.PolicyDecisionPoint', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyDecisionPoint(object):
    """Dịch vụ PDP (Policy Decision Point)
    """

    @staticmethod
    def CheckAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.v1.PolicyDecisionPoint/CheckAccess',
            v1_dot_policy__pb2.CheckAccessRequest.SerializeToString,
            v1_dot_policy__pb2.CheckAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.v1.PolicyDecisionPoint/ExplainDecision',
            v1_dot_policy__pb2.ExplainRequest.SerializeToString,
            v1_dot_policy__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeDelegation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.v1.PolicyDecisionPoint/RevokeDelegation',
            v1_dot_policy__pb2.RevokeRequest.SerializeToString,
            v1_dot_policy__pb2.RevokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
