FROM odoo:17.0@sha256:8779f8157ddcc37b84014c94646073f46fd4ad776b7a5d95fc3b0dc73a24a8fa

USER root
COPY clients/python/requirements.txt /tmp/pdp-client-requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/pdp-client-requirements.txt \
    && rm /tmp/pdp-client-requirements.txt
USER odoo
