FROM odoo:17.0

USER root
COPY clients/python/requirements.txt /tmp/pdp-client-requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/pdp-client-requirements.txt \
    && rm /tmp/pdp-client-requirements.txt
USER odoo
