# Stage 1: Build binary
FROM golang:1.25-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS builder



WORKDIR /app

# Sao chép các file dependency
COPY go.mod go.sum ./
RUN go mod download

# Sao chép toàn bộ mã nguồn
COPY . .

# Biên dịch ứng dụng control-plane
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o control-plane cmd/control-plane/main.go

# Stage 2: Run application
FROM alpine:3.19@sha256:6baf43584bcb78f2e5847d1de515f23499913ac9f12bdf834811a3145eb11ca1

WORKDIR /app

RUN apk --no-cache add ca-certificates

# Copy binary từ stage builder
COPY --from=builder /app/control-plane .
COPY --from=builder /app/db /app/db

RUN addgroup -S -g 10001 pdp \
    && adduser -S -D -H -u 10001 -G pdp pdp \
    && chown -R pdp:pdp /app

# Port mặc định cho HTTP server
EXPOSE 8080

USER pdp

ENTRYPOINT ["./control-plane"]
