# Stage 1: Build binary
FROM golang:1.25-alpine@sha256:1ae0735f00daffa3aaf1363a5184c0d2dc55c78e3db4ec70241cdac97bf84b59 AS builder



WORKDIR /app

# Sao chép các file dependency
COPY go.mod go.sum ./
RUN go mod download

# Sao chép toàn bộ mã nguồn
COPY . .

# Biên dịch ứng dụng pdp-server
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o pdp-server cmd/pdp-server/main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o test-certgen cmd/test-certgen/main.go

# Stage 2: Run application
FROM alpine:3.19@sha256:6baf43584bcb78f2e5847d1de515f23499913ac9f12bdf834811a3145eb11ca1

WORKDIR /app

# Cài đặt ca-certificates để gọi các API HTTPS bên ngoài nếu cần
RUN apk --no-cache add ca-certificates

# Copy binary từ stage builder
COPY --from=builder /app/pdp-server .
COPY --from=builder /app/test-certgen .
COPY --from=builder /app/db /app/db

# Tạo thư mục chứa spill-logs cục bộ và phân quyền ghi
RUN mkdir -p /app/spill-logs && chmod 777 /app/spill-logs

# Khai báo volume cho log spill để persist dữ liệu
VOLUME ["/app/spill-logs"]

# Port mặc định cho gRPC server
EXPOSE 50051

ENTRYPOINT ["./pdp-server"]
