// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessResponse_Decision int32

const (
	CheckAccessResponse_DENY  CheckAccessResponse_Decision = 0
	CheckAccessResponse_ALLOW CheckAccessResponse_Decision = 1
)

// Enum value maps for CheckAccessResponse_Decision.
var (
	CheckAccessResponse_Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	CheckAccessResponse_Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x CheckAccessResponse_Decision) Enum() *CheckAccessResponse_Decision {
	p := new(CheckAccessResponse_Decision)
	*p = x
	return p
}

func (x CheckAccessResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAccessResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_policy_proto_enumTypes[0].Descriptor()
}

func (CheckAccessResponse_Decision) Type() protoreflect.EnumType {
	return &file_v1_policy_proto_enumTypes[0]
}

func (x CheckAccessResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAccessResponse_Decision.Descriptor instead.
func (CheckAccessResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1, 0}
}

type ExplainResponse_Decision int32

const (
	ExplainResponse_DENY  ExplainResponse_Decision = 0
	ExplainResponse_ALLOW ExplainResponse_Decision = 1
)

// Enum value maps for ExplainResponse_Decision.
var (
	ExplainResponse_Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	ExplainResponse_Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x ExplainResponse_Decision) Enum() *ExplainResponse_Decision {
	p := new(ExplainResponse_Decision)
	*p = x
	return p
}

func (x ExplainResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExplainResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_policy_proto_enumTypes[1].Descriptor()
}

func (ExplainResponse_Decision) Type() protoreflect.EnumType {
	return &file_v1_policy_proto_enumTypes[1]
}

func (x ExplainResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExplainResponse_Decision.Descriptor instead.
func (ExplainResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{4, 0}
}

// Yêu cầu kiểm tra quyền truy cập
type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                         // Khóa đa khách thuê (Tenant ID)
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                                                                           // Đối tượng yêu cầu (ví dụ: "user:alice", "role:admin")
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                                                             // Hành động thực hiện (ví dụ: "READ", "DELETE")
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`                                                                         // Tài nguyên tác động (ví dụ: "file:report.pdf")
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Ngữ cảnh thuộc tính động (ví dụ: ip="192.168.1.10", time="08:00:00Z")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckAccessRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckAccessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Phản hồi kết quả kiểm tra quyền truy cập
type CheckAccessResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Decision        CheckAccessResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=policy.v1.CheckAccessResponse_Decision" json:"decision,omitempty"`                          // Quyết định cuối cùng (ALLOW hoặc DENY)
	MatchedPolicyId string                       `protobuf:"bytes,2,opt,name=matched_policy_id,json=matchedPolicyId,proto3" json:"matched_policy_id,omitempty"`                                // ID chính sách quyết định cuối cùng (ALLOW hoặc FORBID)
	Obligations     []*Obligation                `protobuf:"bytes,3,rep,name=obligations,proto3" json:"obligations,omitempty"`                                                                 // Nghĩa vụ có kiểu, thông điệp và payload cho PEP
	Advice          map[string]string            `protobuf:"bytes,4,rep,name=advice,proto3" json:"advice,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata phụ hướng dẫn client (ví dụ: risk_level="HIGH")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetDecision() CheckAccessResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return CheckAccessResponse_DENY
}

func (x *CheckAccessResponse) GetMatchedPolicyId() string {
	if x != nil {
		return x.MatchedPolicyId
	}
	return ""
}

func (x *CheckAccessResponse) GetObligations() []*Obligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *CheckAccessResponse) GetAdvice() map[string]string {
	if x != nil {
		return x.Advice
	}
	return nil
}

type Obligation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obligation) Reset() {
	*x = Obligation{}
	mi := &file_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obligation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obligation) ProtoMessage() {}

func (x *Obligation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obligation.ProtoReflect.Descriptor instead.
func (*Obligation) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Obligation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Obligation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Obligation) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Yêu cầu giải thích chi tiết quyết định
type ExplainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ExplainRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExplainRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ExplainRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ExplainRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Phản hồi giải thích chi tiết quyết định
type ExplainResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Decision      ExplainResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=policy.v1.ExplainResponse_Decision" json:"decision,omitempty"` // Quyết định cuối cùng
	FinalReason   string                   `protobuf:"bytes,2,opt,name=final_reason,json=finalReason,proto3" json:"final_reason,omitempty"`                 // Lý do tổng quát
	Matched       []*PolicyMetadata        `protobuf:"bytes,3,rep,name=matched,proto3" json:"matched,omitempty"`                                            // Danh sách các chính sách đã khớp và thỏa mãn điều kiện
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainResponse) GetDecision() ExplainResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return ExplainResponse_DENY
}

func (x *ExplainResponse) GetFinalReason() string {
	if x != nil {
		return x.FinalReason
	}
	return ""
}

func (x *ExplainResponse) GetMatched() []*PolicyMetadata {
	if x != nil {
		return x.Matched
	}
	return nil
}

// Thông tin chi tiết của một chính sách khớp
type PolicyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Effect        string                 `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`                           // "permit" hoặc "forbid"
	PolicyText    string                 `protobuf:"bytes,3,opt,name=policy_text,json=policyText,proto3" json:"policy_text,omitempty"` // Mã DSL thô của chính sách
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyMetadata) Reset() {
	*x = PolicyMetadata{}
	mi := &file_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyMetadata) ProtoMessage() {}

func (x *PolicyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyMetadata.ProtoReflect.Descriptor instead.
func (*PolicyMetadata) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyMetadata) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyMetadata) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *PolicyMetadata) GetPolicyText() string {
	if x != nil {
		return x.PolicyText
	}
	return ""
}

// Yêu cầu thu hồi ủy quyền của Tác tử AI
type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // Tenant ID (ví dụ: "my_company")
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`       // ID của Delegation Grant (ví dụ: "42")
	RevokedBy     string                 `protobuf:"bytes,3,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"` // Người thực hiện thu hồi (ví dụ: "user:manager_bob")
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                        // Lý do thu hồi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RevokeRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Phản hồi kết quả thu hồi ủy quyền
type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // Kết quả (true/false)
	RevokedAt     int64                  `protobuf:"varint,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"` // Thời điểm thu hồi dạng Unix timestamp
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                       // Thông báo phản hồi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeResponse) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *RevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_policy_proto protoreflect.FileDescriptor

const file_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/policy.proto\x12\tpolicy.v1\"\x81\x02\n" +
	"\x12CheckAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12D\n" +
	"\acontext\x18\x05 \x03(\v2*.policy.v1.CheckAccessRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x02\n" +
	"\x13CheckAccessResponse\x12C\n" +
	"\bdecision\x18\x01 \x01(\x0e2'.policy.v1.CheckAccessResponse.DecisionR\bdecision\x12*\n" +
	"\x11matched_policy_id\x18\x02 \x01(\tR\x0fmatchedPolicyId\x127\n" +
	"\vobligations\x18\x03 \x03(\v2\x15.policy.v1.ObligationR\vobligations\x12B\n" +
	"\x06advice\x18\x04 \x03(\v2*.policy.v1.CheckAccessResponse.AdviceEntryR\x06advice\x1a9\n" +
	"\vAdviceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\"\xb4\x01\n" +
	"\n" +
	"Obligation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\apayload\x18\x03 \x03(\v2\".policy.v1.Obligation.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x0eExplainRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12@\n" +
	"\acontext\x18\x05 \x03(\v2&.policy.v1.ExplainRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x0fExplainResponse\x12?\n" +
	"\bdecision\x18\x01 \x01(\x0e2#.policy.v1.ExplainResponse.DecisionR\bdecision\x12!\n" +
	"\ffinal_reason\x18\x02 \x01(\tR\vfinalReason\x123\n" +
	"\amatched\x18\x03 \x03(\v2\x19.policy.v1.PolicyMetadataR\amatched\"\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\"f\n" +
	"\x0ePolicyMetadata\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x16\n" +
	"\x06effect\x18\x02 \x01(\tR\x06effect\x12\x1f\n" +
	"\vpolicy_text\x18\x03 \x01(\tR\n" +
	"policyText\"~\n" +
	"\rRevokeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x03 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\x03R\trevokedAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf6\x01\n" +
	"\x13PolicyDecisionPoint\x12L\n" +
	"\vCheckAccess\x12\x1d.policy.v1.CheckAccessRequest\x1a\x1e.policy.v1.CheckAccessResponse\x12H\n" +
	"\x0fExplainDecision\x12\x19.policy.v1.ExplainRequest\x1a\x1a.policy.v1.ExplainResponse\x12G\n" +
	"\x10RevokeDelegation\x12\x18.policy.v1.RevokeRequest\x1a\x19.policy.v1.RevokeResponseB,Z*standalone-policy-engine/proto/v1;policyv1b\x06proto3"

var (
	file_v1_policy_proto_rawDescOnce sync.Once
	file_v1_policy_proto_rawDescData []byte
)

func file_v1_policy_proto_rawDescGZIP() []byte {
	file_v1_policy_proto_rawDescOnce.Do(func() {
		file_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)))
	})
	return file_v1_policy_proto_rawDescData
}

var file_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_policy_proto_goTypes = []any{
	(CheckAccessResponse_Decision)(0), // 0: policy.v1.CheckAccessResponse.Decision
	(ExplainResponse_Decision)(0),     // 1: policy.v1.ExplainResponse.Decision
	(*CheckAccessRequest)(nil),        // 2: policy.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),       // 3: policy.v1.CheckAccessResponse
	(*Obligation)(nil),                // 4: policy.v1.Obligation
	(*ExplainRequest)(nil),            // 5: policy.v1.ExplainRequest
	(*ExplainResponse)(nil),           // 6: policy.v1.ExplainResponse
	(*PolicyMetadata)(nil),            // 7: policy.v1.PolicyMetadata
	(*RevokeRequest)(nil),             // 8: policy.v1.RevokeRequest
	(*RevokeResponse)(nil),            // 9: policy.v1.RevokeResponse
	nil,                               // 10: policy.v1.CheckAccessRequest.ContextEntry
	nil,                               // 11: policy.v1.CheckAccessResponse.AdviceEntry
	nil,                               // 12: policy.v1.Obligation.PayloadEntry
	nil,                               // 13: policy.v1.ExplainRequest.ContextEntry
}
var file_v1_policy_proto_depIdxs = []int32{
	10, // 0: policy.v1.CheckAccessRequest.context:type_name -> policy.v1.CheckAccessRequest.ContextEntry
	0,  // 1: policy.v1.CheckAccessResponse.decision:type_name -> policy.v1.CheckAccessResponse.Decision
	4,  // 2: policy.v1.CheckAccessResponse.obligations:type_name -> policy.v1.Obligation
	11, // 3: policy.v1.CheckAccessResponse.advice:type_name -> policy.v1.CheckAccessResponse.AdviceEntry
	12, // 4: policy.v1.Obligation.payload:type_name -> policy.v1.Obligation.PayloadEntry
	13, // 5: policy.v1.ExplainRequest.context:type_name -> policy.v1.ExplainRequest.ContextEntry
	1,  // 6: policy.v1.ExplainResponse.decision:type_name -> policy.v1.ExplainResponse.Decision
	7,  // 7: policy.v1.ExplainResponse.matched:type_name -> policy.v1.PolicyMetadata
	2,  // 8: policy.v1.PolicyDecisionPoint.CheckAccess:input_type -> policy.v1.CheckAccessRequest
	5,  // 9: policy.v1.PolicyDecisionPoint.ExplainDecision:input_type -> policy.v1.ExplainRequest
	8,  // 10: policy.v1.PolicyDecisionPoint.RevokeDelegation:input_type -> policy.v1.RevokeRequest
	3,  // 11: policy.v1.PolicyDecisionPoint.CheckAccess:output_type -> policy.v1.CheckAccessResponse
	6,  // 12: policy.v1.PolicyDecisionPoint.ExplainDecision:output_type -> policy.v1.ExplainResponse
	9,  // 13: policy.v1.PolicyDecisionPoint.RevokeDelegation:output_type -> policy.v1.RevokeResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_policy_proto_init() }
func file_v1_policy_proto_init() {
	if File_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_policy_proto_goTypes,
		DependencyIndexes: file_v1_policy_proto_depIdxs,
		EnumInfos:         file_v1_policy_proto_enumTypes,
		MessageInfos:      file_v1_policy_proto_msgTypes,
	}.Build()
	File_v1_policy_proto = out.File
	file_v1_policy_proto_goTypes = nil
	file_v1_policy_proto_depIdxs = nil
}
