// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/policy.proto

package policyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyDecisionPoint_CheckAccess_FullMethodName      = "/policy.v1.PolicyDecisionPoint/CheckAccess"
	PolicyDecisionPoint_ExplainDecision_FullMethodName  = "/policy.v1.PolicyDecisionPoint/ExplainDecision"
	PolicyDecisionPoint_RevokeDelegation_FullMethodName = "/policy.v1.PolicyDecisionPoint/RevokeDelegation"
)

// PolicyDecisionPointClient is the client API for PolicyDecisionPoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dịch vụ PDP (Policy Decision Point)
type PolicyDecisionPointClient interface {
	// Đánh giá quyền truy cập dựa trên ngữ cảnh động
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
	// Đánh giá quyền kèm giải thích chi tiết các luật áp dụng
	ExplainDecision(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	// Thu hồi phiên ủy quyền của Tác tử AI tức thời (In-Memory Revocation < 1 µs)
	RevokeDelegation(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
}

type policyDecisionPointClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyDecisionPointClient(cc grpc.ClientConnInterface) PolicyDecisionPointClient {
	return &policyDecisionPointClient{cc}
}

func (c *policyDecisionPointClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, PolicyDecisionPoint_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyDecisionPointClient) ExplainDecision(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, PolicyDecisionPoint_ExplainDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyDecisionPointClient) RevokeDelegation(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, PolicyDecisionPoint_RevokeDelegation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyDecisionPointServer is the server API for PolicyDecisionPoint service.
// All implementations must embed UnimplementedPolicyDecisionPointServer
// for forward compatibility.
//
// Dịch vụ PDP (Policy Decision Point)
type PolicyDecisionPointServer interface {
	// Đánh giá quyền truy cập dựa trên ngữ cảnh động
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	// Đánh giá quyền kèm giải thích chi tiết các luật áp dụng
	ExplainDecision(context.Context, *ExplainRequest) (*ExplainResponse, error)
	// Thu hồi phiên ủy quyền của Tác tử AI tức thời (In-Memory Revocation < 1 µs)
	RevokeDelegation(context.Context, *RevokeRequest) (*RevokeResponse, error)
	mustEmbedUnimplementedPolicyDecisionPointServer()
}

// UnimplementedPolicyDecisionPointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyDecisionPointServer struct{}

func (UnimplementedPolicyDecisionPointServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedPolicyDecisionPointServer) ExplainDecision(context.Context, *ExplainRequest) (*ExplainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainDecision not implemented")
}
func (UnimplementedPolicyDecisionPointServer) RevokeDelegation(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDelegation not implemented")
}
func (UnimplementedPolicyDecisionPointServer) mustEmbedUnimplementedPolicyDecisionPointServer() {}
func (UnimplementedPolicyDecisionPointServer) testEmbeddedByValue()                             {}

// UnsafePolicyDecisionPointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyDecisionPointServer will
// result in compilation errors.
type UnsafePolicyDecisionPointServer interface {
	mustEmbedUnimplementedPolicyDecisionPointServer()
}

func RegisterPolicyDecisionPointServer(s grpc.ServiceRegistrar, srv PolicyDecisionPointServer) {
	// If the following call pancis, it indicates UnimplementedPolicyDecisionPointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyDecisionPoint_ServiceDesc, srv)
}

func _PolicyDecisionPoint_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyDecisionPointServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyDecisionPoint_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyDecisionPointServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyDecisionPoint_ExplainDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyDecisionPointServer).ExplainDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyDecisionPoint_ExplainDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyDecisionPointServer).ExplainDecision(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyDecisionPoint_RevokeDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyDecisionPointServer).RevokeDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyDecisionPoint_RevokeDelegation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyDecisionPointServer).RevokeDelegation(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyDecisionPoint_ServiceDesc is the grpc.ServiceDesc for PolicyDecisionPoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyDecisionPoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.v1.PolicyDecisionPoint",
	HandlerType: (*PolicyDecisionPointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _PolicyDecisionPoint_CheckAccess_Handler,
		},
		{
			MethodName: "ExplainDecision",
			Handler:    _PolicyDecisionPoint_ExplainDecision_Handler,
		},
		{
			MethodName: "RevokeDelegation",
			Handler:    _PolicyDecisionPoint_RevokeDelegation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/policy.proto",
}
