// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessResponse_Decision int32

const (
	CheckAccessResponse_DENY  CheckAccessResponse_Decision = 0
	CheckAccessResponse_ALLOW CheckAccessResponse_Decision = 1
)

// Enum value maps for CheckAccessResponse_Decision.
var (
	CheckAccessResponse_Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	CheckAccessResponse_Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x CheckAccessResponse_Decision) Enum() *CheckAccessResponse_Decision {
	p := new(CheckAccessResponse_Decision)
	*p = x
	return p
}

func (x CheckAccessResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAccessResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_policy_proto_enumTypes[0].Descriptor()
}

func (CheckAccessResponse_Decision) Type() protoreflect.EnumType {
	return &file_v1_policy_proto_enumTypes[0]
}

func (x CheckAccessResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAccessResponse_Decision.Descriptor instead.
func (CheckAccessResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1, 0}
}

type ExplainResponse_Decision int32

const (
	ExplainResponse_DENY  ExplainResponse_Decision = 0
	ExplainResponse_ALLOW ExplainResponse_Decision = 1
)

// Enum value maps for ExplainResponse_Decision.
var (
	ExplainResponse_Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	ExplainResponse_Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x ExplainResponse_Decision) Enum() *ExplainResponse_Decision {
	p := new(ExplainResponse_Decision)
	*p = x
	return p
}

func (x ExplainResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExplainResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_policy_proto_enumTypes[1].Descriptor()
}

func (ExplainResponse_Decision) Type() protoreflect.EnumType {
	return &file_v1_policy_proto_enumTypes[1]
}

func (x ExplainResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExplainResponse_Decision.Descriptor instead.
func (ExplainResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{4, 0}
}

// Yêu cầu kiểm tra quyền truy cập
type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                         // Khóa đa khách thuê (Tenant ID)
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                                                                           // Đối tượng yêu cầu (ví dụ: "user:alice", "role:admin")
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                                                             // Hành động thực hiện (ví dụ: "READ", "DELETE")
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`                                                                         // Tài nguyên tác động (ví dụ: "file:report.pdf")
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Ngữ cảnh thuộc tính động (ví dụ: ip="192.168.1.10", time="08:00:00Z")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckAccessRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckAccessRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Phản hồi kết quả kiểm tra quyền truy cập
type CheckAccessResponse struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Decision        CheckAccessResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=policy.v1.CheckAccessResponse_Decision" json:"decision,omitempty"`                          // Quyết định cuối cùng (ALLOW hoặc DENY)
	MatchedPolicyId string                       `protobuf:"bytes,2,opt,name=matched_policy_id,json=matchedPolicyId,proto3" json:"matched_policy_id,omitempty"`                                // ID chính sách quyết định cuối cùng (ALLOW hoặc FORBID)
	Obligations     []*Obligation                `protobuf:"bytes,3,rep,name=obligations,proto3" json:"obligations,omitempty"`                                                                 // Nghĩa vụ có kiểu, thông điệp và payload cho PEP
	Advice          map[string]string            `protobuf:"bytes,4,rep,name=advice,proto3" json:"advice,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Metadata phụ hướng dẫn client (ví dụ: risk_level="HIGH")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetDecision() CheckAccessResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return CheckAccessResponse_DENY
}

func (x *CheckAccessResponse) GetMatchedPolicyId() string {
	if x != nil {
		return x.MatchedPolicyId
	}
	return ""
}

func (x *CheckAccessResponse) GetObligations() []*Obligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *CheckAccessResponse) GetAdvice() map[string]string {
	if x != nil {
		return x.Advice
	}
	return nil
}

type Obligation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obligation) Reset() {
	*x = Obligation{}
	mi := &file_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obligation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obligation) ProtoMessage() {}

func (x *Obligation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obligation.ProtoReflect.Descriptor instead.
func (*Obligation) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Obligation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Obligation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Obligation) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Yêu cầu giải thích chi tiết quyết định
type ExplainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ExplainRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExplainRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ExplainRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExplainRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ExplainRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// Phản hồi giải thích chi tiết quyết định
type ExplainResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Decision      ExplainResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=policy.v1.ExplainResponse_Decision" json:"decision,omitempty"` // Quyết định cuối cùng
	FinalReason   string                   `protobuf:"bytes,2,opt,name=final_reason,json=finalReason,proto3" json:"final_reason,omitempty"`                 // Lý do tổng quát
	Matched       []*PolicyMetadata        `protobuf:"bytes,3,rep,name=matched,proto3" json:"matched,omitempty"`                                            // Danh sách các chính sách đã khớp và thỏa mãn điều kiện
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ExplainResponse) GetDecision() ExplainResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return ExplainResponse_DENY
}

func (x *ExplainResponse) GetFinalReason() string {
	if x != nil {
		return x.FinalReason
	}
	return ""
}

func (x *ExplainResponse) GetMatched() []*PolicyMetadata {
	if x != nil {
		return x.Matched
	}
	return nil
}

// Thông tin chi tiết của một chính sách khớp
type PolicyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Effect        string                 `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`                           // "permit" hoặc "forbid"
	PolicyText    string                 `protobuf:"bytes,3,opt,name=policy_text,json=policyText,proto3" json:"policy_text,omitempty"` // Mã DSL thô của chính sách
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyMetadata) Reset() {
	*x = PolicyMetadata{}
	mi := &file_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyMetadata) ProtoMessage() {}

func (x *PolicyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyMetadata.ProtoReflect.Descriptor instead.
func (*PolicyMetadata) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyMetadata) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyMetadata) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *PolicyMetadata) GetPolicyText() string {
	if x != nil {
		return x.PolicyText
	}
	return ""
}

// Yêu cầu thu hồi ủy quyền của Tác tử AI
type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // Tenant ID (ví dụ: "my_company")
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`       // ID của Delegation Grant (ví dụ: "42")
	RevokedBy     string                 `protobuf:"bytes,3,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"` // Người thực hiện thu hồi (ví dụ: "user:manager_bob")
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                        // Lý do thu hồi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RevokeRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Phản hồi kết quả thu hồi ủy quyền
type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // Kết quả (true/false)
	RevokedAt     int64                  `protobuf:"varint,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"` // Thời điểm thu hồi dạng Unix timestamp
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                       // Thông báo phản hồi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeResponse) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *RevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApprovalCapability struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CapabilityVersion      string                 `protobuf:"bytes,1,opt,name=capability_version,json=capabilityVersion,proto3" json:"capability_version,omitempty"`
	Purpose                string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ApprovalId             string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	TenantId               string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompanyId              int64                  `protobuf:"varint,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	IntentHash             string                 `protobuf:"bytes,6,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	StateWitness           string                 `protobuf:"bytes,7,opt,name=state_witness,json=stateWitness,proto3" json:"state_witness,omitempty"`
	CommandId              string                 `protobuf:"bytes,8,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DelegationGrantId      int64                  `protobuf:"varint,9,opt,name=delegation_grant_id,json=delegationGrantId,proto3" json:"delegation_grant_id,omitempty"`
	DelegatorSubject       string                 `protobuf:"bytes,10,opt,name=delegator_subject,json=delegatorSubject,proto3" json:"delegator_subject,omitempty"`
	AgentSubject           string                 `protobuf:"bytes,11,opt,name=agent_subject,json=agentSubject,proto3" json:"agent_subject,omitempty"`
	CreatorSubject         string                 `protobuf:"bytes,12,opt,name=creator_subject,json=creatorSubject,proto3" json:"creator_subject,omitempty"`
	ApproverUserId         int64                  `protobuf:"varint,13,opt,name=approver_user_id,json=approverUserId,proto3" json:"approver_user_id,omitempty"`
	ApproverSubject        string                 `protobuf:"bytes,14,opt,name=approver_subject,json=approverSubject,proto3" json:"approver_subject,omitempty"`
	RequiredPermission     string                 `protobuf:"bytes,15,opt,name=required_permission,json=requiredPermission,proto3" json:"required_permission,omitempty"`
	IssuancePolicyRevision int64                  `protobuf:"varint,16,opt,name=issuance_policy_revision,json=issuancePolicyRevision,proto3" json:"issuance_policy_revision,omitempty"`
	IssuedAt               int64                  `protobuf:"varint,17,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt              int64                  `protobuf:"varint,18,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	OneTimeId              string                 `protobuf:"bytes,19,opt,name=one_time_id,json=oneTimeId,proto3" json:"one_time_id,omitempty"`
	Algorithm              string                 `protobuf:"bytes,20,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KeyId                  string                 `protobuf:"bytes,21,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CanonicalPayload       []byte                 `protobuf:"bytes,22,opt,name=canonical_payload,json=canonicalPayload,proto3" json:"canonical_payload,omitempty"`
	Signature              []byte                 `protobuf:"bytes,23,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ApprovalCapability) Reset() {
	*x = ApprovalCapability{}
	mi := &file_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalCapability) ProtoMessage() {}

func (x *ApprovalCapability) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalCapability.ProtoReflect.Descriptor instead.
func (*ApprovalCapability) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *ApprovalCapability) GetCapabilityVersion() string {
	if x != nil {
		return x.CapabilityVersion
	}
	return ""
}

func (x *ApprovalCapability) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ApprovalCapability) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalCapability) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApprovalCapability) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *ApprovalCapability) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *ApprovalCapability) GetStateWitness() string {
	if x != nil {
		return x.StateWitness
	}
	return ""
}

func (x *ApprovalCapability) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ApprovalCapability) GetDelegationGrantId() int64 {
	if x != nil {
		return x.DelegationGrantId
	}
	return 0
}

func (x *ApprovalCapability) GetDelegatorSubject() string {
	if x != nil {
		return x.DelegatorSubject
	}
	return ""
}

func (x *ApprovalCapability) GetAgentSubject() string {
	if x != nil {
		return x.AgentSubject
	}
	return ""
}

func (x *ApprovalCapability) GetCreatorSubject() string {
	if x != nil {
		return x.CreatorSubject
	}
	return ""
}

func (x *ApprovalCapability) GetApproverUserId() int64 {
	if x != nil {
		return x.ApproverUserId
	}
	return 0
}

func (x *ApprovalCapability) GetApproverSubject() string {
	if x != nil {
		return x.ApproverSubject
	}
	return ""
}

func (x *ApprovalCapability) GetRequiredPermission() string {
	if x != nil {
		return x.RequiredPermission
	}
	return ""
}

func (x *ApprovalCapability) GetIssuancePolicyRevision() int64 {
	if x != nil {
		return x.IssuancePolicyRevision
	}
	return 0
}

func (x *ApprovalCapability) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *ApprovalCapability) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ApprovalCapability) GetOneTimeId() string {
	if x != nil {
		return x.OneTimeId
	}
	return ""
}

func (x *ApprovalCapability) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ApprovalCapability) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ApprovalCapability) GetCanonicalPayload() []byte {
	if x != nil {
		return x.CanonicalPayload
	}
	return nil
}

func (x *ApprovalCapability) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type IssueApprovalCapabilityRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TenantId             string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CompanyId            int64                  `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ApprovalId           string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	IntentHash           string                 `protobuf:"bytes,4,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	StateWitness         string                 `protobuf:"bytes,5,opt,name=state_witness,json=stateWitness,proto3" json:"state_witness,omitempty"`
	CommandId            string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	DelegationGrantId    int64                  `protobuf:"varint,7,opt,name=delegation_grant_id,json=delegationGrantId,proto3" json:"delegation_grant_id,omitempty"`
	DelegatorSubject     string                 `protobuf:"bytes,8,opt,name=delegator_subject,json=delegatorSubject,proto3" json:"delegator_subject,omitempty"`
	AgentSubject         string                 `protobuf:"bytes,9,opt,name=agent_subject,json=agentSubject,proto3" json:"agent_subject,omitempty"`
	CreatorSubject       string                 `protobuf:"bytes,10,opt,name=creator_subject,json=creatorSubject,proto3" json:"creator_subject,omitempty"`
	ApproverUserId       int64                  `protobuf:"varint,11,opt,name=approver_user_id,json=approverUserId,proto3" json:"approver_user_id,omitempty"`
	Resource             string                 `protobuf:"bytes,12,opt,name=resource,proto3" json:"resource,omitempty"`
	DelegationValidUntil int64                  `protobuf:"varint,13,opt,name=delegation_valid_until,json=delegationValidUntil,proto3" json:"delegation_valid_until,omitempty"`
	Context              map[string]string      `protobuf:"bytes,14,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IssueApprovalCapabilityRequest) Reset() {
	*x = IssueApprovalCapabilityRequest{}
	mi := &file_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApprovalCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApprovalCapabilityRequest) ProtoMessage() {}

func (x *IssueApprovalCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApprovalCapabilityRequest.ProtoReflect.Descriptor instead.
func (*IssueApprovalCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *IssueApprovalCapabilityRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *IssueApprovalCapabilityRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetIntentHash() string {
	if x != nil {
		return x.IntentHash
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetStateWitness() string {
	if x != nil {
		return x.StateWitness
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetDelegationGrantId() int64 {
	if x != nil {
		return x.DelegationGrantId
	}
	return 0
}

func (x *IssueApprovalCapabilityRequest) GetDelegatorSubject() string {
	if x != nil {
		return x.DelegatorSubject
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetAgentSubject() string {
	if x != nil {
		return x.AgentSubject
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetCreatorSubject() string {
	if x != nil {
		return x.CreatorSubject
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetApproverUserId() int64 {
	if x != nil {
		return x.ApproverUserId
	}
	return 0
}

func (x *IssueApprovalCapabilityRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *IssueApprovalCapabilityRequest) GetDelegationValidUntil() int64 {
	if x != nil {
		return x.DelegationValidUntil
	}
	return 0
}

func (x *IssueApprovalCapabilityRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type IssueApprovalCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    *ApprovalCapability    `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueApprovalCapabilityResponse) Reset() {
	*x = IssueApprovalCapabilityResponse{}
	mi := &file_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueApprovalCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueApprovalCapabilityResponse) ProtoMessage() {}

func (x *IssueApprovalCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueApprovalCapabilityResponse.ProtoReflect.Descriptor instead.
func (*IssueApprovalCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *IssueApprovalCapabilityResponse) GetCapability() *ApprovalCapability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type VerifyApprovalCapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Capability    *ApprovalCapability    `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApprovalCapabilityRequest) Reset() {
	*x = VerifyApprovalCapabilityRequest{}
	mi := &file_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApprovalCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApprovalCapabilityRequest) ProtoMessage() {}

func (x *VerifyApprovalCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApprovalCapabilityRequest.ProtoReflect.Descriptor instead.
func (*VerifyApprovalCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyApprovalCapabilityRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyApprovalCapabilityRequest) GetCapability() *ApprovalCapability {
	if x != nil {
		return x.Capability
	}
	return nil
}

type VerifyApprovalCapabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApprovalCapabilityResponse) Reset() {
	*x = VerifyApprovalCapabilityResponse{}
	mi := &file_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApprovalCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApprovalCapabilityResponse) ProtoMessage() {}

func (x *VerifyApprovalCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApprovalCapabilityResponse.ProtoReflect.Descriptor instead.
func (*VerifyApprovalCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyApprovalCapabilityResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_v1_policy_proto protoreflect.FileDescriptor

const file_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/policy.proto\x12\tpolicy.v1\"\x81\x02\n" +
	"\x12CheckAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12D\n" +
	"\acontext\x18\x05 \x03(\v2*.policy.v1.CheckAccessRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x02\n" +
	"\x13CheckAccessResponse\x12C\n" +
	"\bdecision\x18\x01 \x01(\x0e2'.policy.v1.CheckAccessResponse.DecisionR\bdecision\x12*\n" +
	"\x11matched_policy_id\x18\x02 \x01(\tR\x0fmatchedPolicyId\x127\n" +
	"\vobligations\x18\x03 \x03(\v2\x15.policy.v1.ObligationR\vobligations\x12B\n" +
	"\x06advice\x18\x04 \x03(\v2*.policy.v1.CheckAccessResponse.AdviceEntryR\x06advice\x1a9\n" +
	"\vAdviceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\"\xb4\x01\n" +
	"\n" +
	"Obligation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\apayload\x18\x03 \x03(\v2\".policy.v1.Obligation.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x0eExplainRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12@\n" +
	"\acontext\x18\x05 \x03(\v2&.policy.v1.ExplainRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x0fExplainResponse\x12?\n" +
	"\bdecision\x18\x01 \x01(\x0e2#.policy.v1.ExplainResponse.DecisionR\bdecision\x12!\n" +
	"\ffinal_reason\x18\x02 \x01(\tR\vfinalReason\x123\n" +
	"\amatched\x18\x03 \x03(\v2\x19.policy.v1.PolicyMetadataR\amatched\"\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\"f\n" +
	"\x0ePolicyMetadata\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x16\n" +
	"\x06effect\x18\x02 \x01(\tR\x06effect\x12\x1f\n" +
	"\vpolicy_text\x18\x03 \x01(\tR\n" +
	"policyText\"~\n" +
	"\rRevokeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x03 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\x03R\trevokedAt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe6\x06\n" +
	"\x12ApprovalCapability\x12-\n" +
	"\x12capability_version\x18\x01 \x01(\tR\x11capabilityVersion\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\x03R\tcompanyId\x12\x1f\n" +
	"\vintent_hash\x18\x06 \x01(\tR\n" +
	"intentHash\x12#\n" +
	"\rstate_witness\x18\a \x01(\tR\fstateWitness\x12\x1d\n" +
	"\n" +
	"command_id\x18\b \x01(\tR\tcommandId\x12.\n" +
	"\x13delegation_grant_id\x18\t \x01(\x03R\x11delegationGrantId\x12+\n" +
	"\x11delegator_subject\x18\n" +
	" \x01(\tR\x10delegatorSubject\x12#\n" +
	"\ragent_subject\x18\v \x01(\tR\fagentSubject\x12'\n" +
	"\x0fcreator_subject\x18\f \x01(\tR\x0ecreatorSubject\x12(\n" +
	"\x10approver_user_id\x18\r \x01(\x03R\x0eapproverUserId\x12)\n" +
	"\x10approver_subject\x18\x0e \x01(\tR\x0fapproverSubject\x12/\n" +
	"\x13required_permission\x18\x0f \x01(\tR\x12requiredPermission\x128\n" +
	"\x18issuance_policy_revision\x18\x10 \x01(\x03R\x16issuancePolicyRevision\x12\x1b\n" +
	"\tissued_at\x18\x11 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x12 \x01(\x03R\texpiresAt\x12\x1e\n" +
	"\vone_time_id\x18\x13 \x01(\tR\toneTimeId\x12\x1c\n" +
	"\talgorithm\x18\x14 \x01(\tR\talgorithm\x12\x15\n" +
	"\x06key_id\x18\x15 \x01(\tR\x05keyId\x12+\n" +
	"\x11canonical_payload\x18\x16 \x01(\fR\x10canonicalPayload\x12\x1c\n" +
	"\tsignature\x18\x17 \x01(\fR\tsignature\"\x97\x05\n" +
	"\x1eIssueApprovalCapabilityRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x03R\tcompanyId\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\x12\x1f\n" +
	"\vintent_hash\x18\x04 \x01(\tR\n" +
	"intentHash\x12#\n" +
	"\rstate_witness\x18\x05 \x01(\tR\fstateWitness\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\x12.\n" +
	"\x13delegation_grant_id\x18\a \x01(\x03R\x11delegationGrantId\x12+\n" +
	"\x11delegator_subject\x18\b \x01(\tR\x10delegatorSubject\x12#\n" +
	"\ragent_subject\x18\t \x01(\tR\fagentSubject\x12'\n" +
	"\x0fcreator_subject\x18\n" +
	" \x01(\tR\x0ecreatorSubject\x12(\n" +
	"\x10approver_user_id\x18\v \x01(\x03R\x0eapproverUserId\x12\x1a\n" +
	"\bresource\x18\f \x01(\tR\bresource\x124\n" +
	"\x16delegation_valid_until\x18\r \x01(\x03R\x14delegationValidUntil\x12P\n" +
	"\acontext\x18\x0e \x03(\v26.policy.v1.IssueApprovalCapabilityRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x1fIssueApprovalCapabilityResponse\x12=\n" +
	"\n" +
	"capability\x18\x01 \x01(\v2\x1d.policy.v1.ApprovalCapabilityR\n" +
	"capability\"}\n" +
	"\x1fVerifyApprovalCapabilityRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12=\n" +
	"\n" +
	"capability\x18\x02 \x01(\v2\x1d.policy.v1.ApprovalCapabilityR\n" +
	"capability\"8\n" +
	" VerifyApprovalCapabilityResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xdd\x03\n" +
	"\x13PolicyDecisionPoint\x12L\n" +
	"\vCheckAccess\x12\x1d.policy.v1.CheckAccessRequest\x1a\x1e.policy.v1.CheckAccessResponse\x12H\n" +
	"\x0fExplainDecision\x12\x19.policy.v1.ExplainRequest\x1a\x1a.policy.v1.ExplainResponse\x12G\n" +
	"\x10RevokeDelegation\x12\x18.policy.v1.RevokeRequest\x1a\x19.policy.v1.RevokeResponse\x12p\n" +
	"\x17IssueApprovalCapability\x12).policy.v1.IssueApprovalCapabilityRequest\x1a*.policy.v1.IssueApprovalCapabilityResponse\x12s\n" +
	"\x18VerifyApprovalCapability\x12*.policy.v1.VerifyApprovalCapabilityRequest\x1a+.policy.v1.VerifyApprovalCapabilityResponseB,Z*standalone-policy-engine/proto/v1;policyv1b\x06proto3"

var (
	file_v1_policy_proto_rawDescOnce sync.Once
	file_v1_policy_proto_rawDescData []byte
)

func file_v1_policy_proto_rawDescGZIP() []byte {
	file_v1_policy_proto_rawDescOnce.Do(func() {
		file_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)))
	})
	return file_v1_policy_proto_rawDescData
}

var file_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_policy_proto_goTypes = []any{
	(CheckAccessResponse_Decision)(0),        // 0: policy.v1.CheckAccessResponse.Decision
	(ExplainResponse_Decision)(0),            // 1: policy.v1.ExplainResponse.Decision
	(*CheckAccessRequest)(nil),               // 2: policy.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),              // 3: policy.v1.CheckAccessResponse
	(*Obligation)(nil),                       // 4: policy.v1.Obligation
	(*ExplainRequest)(nil),                   // 5: policy.v1.ExplainRequest
	(*ExplainResponse)(nil),                  // 6: policy.v1.ExplainResponse
	(*PolicyMetadata)(nil),                   // 7: policy.v1.PolicyMetadata
	(*RevokeRequest)(nil),                    // 8: policy.v1.RevokeRequest
	(*RevokeResponse)(nil),                   // 9: policy.v1.RevokeResponse
	(*ApprovalCapability)(nil),               // 10: policy.v1.ApprovalCapability
	(*IssueApprovalCapabilityRequest)(nil),   // 11: policy.v1.IssueApprovalCapabilityRequest
	(*IssueApprovalCapabilityResponse)(nil),  // 12: policy.v1.IssueApprovalCapabilityResponse
	(*VerifyApprovalCapabilityRequest)(nil),  // 13: policy.v1.VerifyApprovalCapabilityRequest
	(*VerifyApprovalCapabilityResponse)(nil), // 14: policy.v1.VerifyApprovalCapabilityResponse
	nil,                                      // 15: policy.v1.CheckAccessRequest.ContextEntry
	nil,                                      // 16: policy.v1.CheckAccessResponse.AdviceEntry
	nil,                                      // 17: policy.v1.Obligation.PayloadEntry
	nil,                                      // 18: policy.v1.ExplainRequest.ContextEntry
	nil,                                      // 19: policy.v1.IssueApprovalCapabilityRequest.ContextEntry
}
var file_v1_policy_proto_depIdxs = []int32{
	15, // 0: policy.v1.CheckAccessRequest.context:type_name -> policy.v1.CheckAccessRequest.ContextEntry
	0,  // 1: policy.v1.CheckAccessResponse.decision:type_name -> policy.v1.CheckAccessResponse.Decision
	4,  // 2: policy.v1.CheckAccessResponse.obligations:type_name -> policy.v1.Obligation
	16, // 3: policy.v1.CheckAccessResponse.advice:type_name -> policy.v1.CheckAccessResponse.AdviceEntry
	17, // 4: policy.v1.Obligation.payload:type_name -> policy.v1.Obligation.PayloadEntry
	18, // 5: policy.v1.ExplainRequest.context:type_name -> policy.v1.ExplainRequest.ContextEntry
	1,  // 6: policy.v1.ExplainResponse.decision:type_name -> policy.v1.ExplainResponse.Decision
	7,  // 7: policy.v1.ExplainResponse.matched:type_name -> policy.v1.PolicyMetadata
	19, // 8: policy.v1.IssueApprovalCapabilityRequest.context:type_name -> policy.v1.IssueApprovalCapabilityRequest.ContextEntry
	10, // 9: policy.v1.IssueApprovalCapabilityResponse.capability:type_name -> policy.v1.ApprovalCapability
	10, // 10: policy.v1.VerifyApprovalCapabilityRequest.capability:type_name -> policy.v1.ApprovalCapability
	2,  // 11: policy.v1.PolicyDecisionPoint.CheckAccess:input_type -> policy.v1.CheckAccessRequest
	5,  // 12: policy.v1.PolicyDecisionPoint.ExplainDecision:input_type -> policy.v1.ExplainRequest
	8,  // 13: policy.v1.PolicyDecisionPoint.RevokeDelegation:input_type -> policy.v1.RevokeRequest
	11, // 14: policy.v1.PolicyDecisionPoint.IssueApprovalCapability:input_type -> policy.v1.IssueApprovalCapabilityRequest
	13, // 15: policy.v1.PolicyDecisionPoint.VerifyApprovalCapability:input_type -> policy.v1.VerifyApprovalCapabilityRequest
	3,  // 16: policy.v1.PolicyDecisionPoint.CheckAccess:output_type -> policy.v1.CheckAccessResponse
	6,  // 17: policy.v1.PolicyDecisionPoint.ExplainDecision:output_type -> policy.v1.ExplainResponse
	9,  // 18: policy.v1.PolicyDecisionPoint.RevokeDelegation:output_type -> policy.v1.RevokeResponse
	12, // 19: policy.v1.PolicyDecisionPoint.IssueApprovalCapability:output_type -> policy.v1.IssueApprovalCapabilityResponse
	14, // 20: policy.v1.PolicyDecisionPoint.VerifyApprovalCapability:output_type -> policy.v1.VerifyApprovalCapabilityResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_policy_proto_init() }
func file_v1_policy_proto_init() {
	if File_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_policy_proto_rawDesc), len(file_v1_policy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_policy_proto_goTypes,
		DependencyIndexes: file_v1_policy_proto_depIdxs,
		EnumInfos:         file_v1_policy_proto_enumTypes,
		MessageInfos:      file_v1_policy_proto_msgTypes,
	}.Build()
	File_v1_policy_proto = out.File
	file_v1_policy_proto_goTypes = nil
	file_v1_policy_proto_depIdxs = nil
}
